version: '3.8'
services:
  # Database
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: hostking
      POSTGRES_USER: hostkinguser
      POSTGRES_PASSWORD: hostkingpass
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=hostkinguser
      - DB_PASSWORD=hostkingpass
      - DB_DATABASE=hostking
      - JWT_SECRET=your_jwt_secret_key_here
      - SESSION_SECRET=your_session_secret_key_here
      - REDIS_URL=redis://redis:6379
    volumes:
      - type: bind
        source: ./backend/logs
        target: /app/logs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local 