version: '3.8'
services:
  # Database
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: hostking
      POSTGRES_USER: hostkinguser
      POSTGRES_PASSWORD: hostkingpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=hostkinguser
      - DB_PASSWORD=hostkingpass
      - DB_DATABASE=hostking
      - JWT_SECRET=your_jwt_secret
      - SESSION_SECRET=your_session_secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data: 